Checking revoke and delete states
lyrasis/simplye-Android-Core pull request #8
Opened 2021-04-29 12:59 UTC by talesgurjao

**What's this do?**
Proper check before enabling "Return" and "Delete" buttons

**Why are we doing this? (w/ JIRA link if applicable)**
https://www.notion.so/lyrasis/Returning-a-deleted-book-results-in-error-517abbf9d7eb4e96b492a889bc2447a8

**How should this be tested? / Do these changes have associated tests?**
Download any book, open the details, then delete it and check if you can still return the book

**Dependencies for merging? Releasing to production?**
None

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
@talesgurjao

2021-05-04 03:37 UTC, ray-lee requested changes

2021-05-04 03:37 UTC, ray-lee commented on simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFragmentBookDetail.kt
> +      return if (book.isDownloaded && account.bookDatabase.books().contains(book.id)) {
I understand why you're doing this, but I'm worried that there's some edge case that was being handled by allowing the delete without download. I think we should be conservative and leave this the same for now, since your other change is enough to prevent the error.

2021-05-04 03:37 UTC, ray-lee commented on simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFragmentBookDetail.kt
> +
👍

2021-05-05 14:11 UTC, talesgurjao commented on simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFragmentBookDetail.kt
> +      return if (book.isDownloaded && account.bookDatabase.books().contains(book.id)) {
Fixed now

2021-05-05 23:17 UTC, ray-lee commented
Thanks!

2021-05-05 23:17 UTC, merged